$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1528176123659.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2fbcec0a648d47bc975e564564b73a76",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d55eb7a8c154465b874dba0d643c2810",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0D0D0D},
{
                  "color":0xFF0D0D0D},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":-20,
              "y":0},
            "size":{
              "width":1370,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfc8486046aa414fb06dc148c6b18287",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0D0D0D},
{
                      "color":0xFF0D0D0D},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":-20,
                  "y":0},
                "size":{
                  "width":1370,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"258ff13fdb4549f99be66f294ba1b3c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":54,
              "y":20},
            "size":{
              "width":67,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec3c558c2ee4505a5b1941f831ed125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":20},
                "size":{
                  "width":67,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58d13f17276d48489c08db2e252df796",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":420,
              "y":20},
            "size":{
              "width":81,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fec08e554c5849d3813cc475d56193bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":20},
                "size":{
                  "width":81,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9030a1574e994f20be2960a35d38c549",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6600FF},
            "location":{
              "x":370,
              "y":164},
            "size":{
              "width":380,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2dc0c7443d045be823a36f63981286e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6600FF},
                "location":{
                  "x":370,
                  "y":164},
                "size":{
                  "width":380,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"6fd39339675b4cd7bbe45519cc2216ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":531,
              "y":195},
            "size":{
              "width":94,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30b63643eefa4a7d96812ea96c153876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":531,
                  "y":195},
                "size":{
                  "width":94,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fd24d43115a4dd5a0d9c2deddf311be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":862,
              "y":22},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"475456eaac804cc98a1a6cbb6438051a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":862,
                  "y":22},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3e18caf29c44ba2a010d00a66fd6566",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":963,
              "y":22},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f51efc572f8d41c2a5f560c789bf381c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":963,
                  "y":22},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"861f8137f8404ab3b2a48d8aba921021",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":410,
              "y":267},
            "size":{
              "width":72,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2ad679c7ff147fcb519ccab906274b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":267},
                "size":{
                  "width":72,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u14.png"}},
{
          "id":"1e9699d47e4744e5a811db6c7c84e44a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":267},
            "size":{
              "width":230,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74f6e0a5e67c4730937140099ec32a0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":267},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u16.png"}},
{
          "id":"37e3f843168f41c2b6a6330bc714a42e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":410,
              "y":359},
            "size":{
              "width":72,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8241675f954248e9a83bb750fd3a2711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":359},
                "size":{
                  "width":72,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u14.png"}},
{
          "id":"79b23aa77cdf486bb78cd97c79398b40",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":359},
            "size":{
              "width":230,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e6197e32c94da7ae6c723df676be2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":359},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u16.png"}},
{
          "id":"592acc828a1c4b9ca505a3241103d0c6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":447,
              "y":435},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af0e73a3ce2242f89fc08fe9b5b109aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":447,
                  "y":435},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"5769b1da2e9f4e7fb1a3fe66904e1539",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":593,
              "y":435},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9874c3fbc53348df83cb3456f88c1f4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":593,
                  "y":435},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"f5d9d6397a9648f9ac58004dcaec32a8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":510,
              "y":504},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "d55eb7a8c154465b874dba0d643c2810":{
      "scriptId":"u0"},
    "bfc8486046aa414fb06dc148c6b18287":{
      "scriptId":"u1"},
    "258ff13fdb4549f99be66f294ba1b3c4":{
      "scriptId":"u2"},
    "0ec3c558c2ee4505a5b1941f831ed125":{
      "scriptId":"u3"},
    "58d13f17276d48489c08db2e252df796":{
      "scriptId":"u4"},
    "fec08e554c5849d3813cc475d56193bf":{
      "scriptId":"u5"},
    "9030a1574e994f20be2960a35d38c549":{
      "scriptId":"u6"},
    "c2dc0c7443d045be823a36f63981286e":{
      "scriptId":"u7"},
    "6fd39339675b4cd7bbe45519cc2216ac":{
      "scriptId":"u8"},
    "30b63643eefa4a7d96812ea96c153876":{
      "scriptId":"u9"},
    "8fd24d43115a4dd5a0d9c2deddf311be":{
      "scriptId":"u10"},
    "475456eaac804cc98a1a6cbb6438051a":{
      "scriptId":"u11"},
    "b3e18caf29c44ba2a010d00a66fd6566":{
      "scriptId":"u12"},
    "f51efc572f8d41c2a5f560c789bf381c":{
      "scriptId":"u13"},
    "861f8137f8404ab3b2a48d8aba921021":{
      "scriptId":"u14"},
    "c2ad679c7ff147fcb519ccab906274b9":{
      "scriptId":"u15"},
    "1e9699d47e4744e5a811db6c7c84e44a":{
      "scriptId":"u16"},
    "74f6e0a5e67c4730937140099ec32a0c":{
      "scriptId":"u17"},
    "37e3f843168f41c2b6a6330bc714a42e":{
      "scriptId":"u18"},
    "8241675f954248e9a83bb750fd3a2711":{
      "scriptId":"u19"},
    "79b23aa77cdf486bb78cd97c79398b40":{
      "scriptId":"u20"},
    "e0e6197e32c94da7ae6c723df676be2c":{
      "scriptId":"u21"},
    "592acc828a1c4b9ca505a3241103d0c6":{
      "scriptId":"u22"},
    "af0e73a3ce2242f89fc08fe9b5b109aa":{
      "scriptId":"u23"},
    "5769b1da2e9f4e7fb1a3fe66904e1539":{
      "scriptId":"u24"},
    "9874c3fbc53348df83cb3456f88c1f4e":{
      "scriptId":"u25"},
    "f5d9d6397a9648f9ac58004dcaec32a8":{
      "scriptId":"u26"}}});