$axure.loadCurrentPage({
  "url":"查看用户信息.html",
  "generationDate":new Date(1528176123596.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"75eba1645165460b9575c1ca6d5f7d21",
    "type":"Axure:Page",
    "name":"查看用户信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d51dd4ecd7d8470fb44298e2bd4cfa81",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0D0D0D},
{
                  "color":0xFF0D0D0D},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":-20,
              "y":0},
            "size":{
              "width":1130,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e801e23548400ca46447edca4bd166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0D0D0D},
{
                      "color":0xFF0D0D0D},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":-20,
                  "y":0},
                "size":{
                  "width":1130,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看成绩/u0.png"}},
{
          "id":"44ce72a3ea0b405bb03533e0be4916ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":54,
              "y":20},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d10c0af9d22c483092d0126486b3c333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":20},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc775c82bbf544e3bc62d384ccfeef5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":346,
              "y":21},
            "size":{
              "width":67,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f81dad92ab0f4caba7d3e3641e75f770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":21},
                "size":{
                  "width":67,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64afd9c1d07d406e90ce9f6ae9376c66",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":294,
              "y":196},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b3d315a60d4af8b6255a3592df0f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":294,
                  "y":196},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c8e7752cd79443b83116ee4086fc572",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":196},
            "size":{
              "width":314,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a7f589fa689459ea471741386862155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":196},
                "size":{
                  "width":314,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/u8.png"}},
{
          "id":"3b15317b990444c1a6a111cbd126da5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":294,
              "y":260},
            "size":{
              "width":85,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f385d554606d4264b675424bb19bde93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":294,
                  "y":260},
                "size":{
                  "width":85,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b5f1a9b40884dd397b5c19239173a09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":260},
            "size":{
              "width":314,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df4ae7d7e6c48bbb040528932c829ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":260},
                "size":{
                  "width":314,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/u8.png"}},
{
          "id":"c68be6fa2a6a4d878b85ba21fb516075",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":115,
              "y":20},
            "size":{
              "width":181,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9cbd6f5f73944d5b3f15f4465525ab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":20},
                "size":{
                  "width":181,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a9fef5c1b404a35a786b9544f759c30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":570,
              "y":21},
            "size":{
              "width":81,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0f833565eb34917b759ca80de53e059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":21},
                "size":{
                  "width":81,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"938bc09828af4f259271db4b363b5d6e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":390},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "d51dd4ecd7d8470fb44298e2bd4cfa81":{
      "scriptId":"u0"},
    "70e801e23548400ca46447edca4bd166":{
      "scriptId":"u1"},
    "44ce72a3ea0b405bb03533e0be4916ce":{
      "scriptId":"u2"},
    "d10c0af9d22c483092d0126486b3c333":{
      "scriptId":"u3"},
    "cc775c82bbf544e3bc62d384ccfeef5e":{
      "scriptId":"u4"},
    "f81dad92ab0f4caba7d3e3641e75f770":{
      "scriptId":"u5"},
    "64afd9c1d07d406e90ce9f6ae9376c66":{
      "scriptId":"u6"},
    "88b3d315a60d4af8b6255a3592df0f18":{
      "scriptId":"u7"},
    "9c8e7752cd79443b83116ee4086fc572":{
      "scriptId":"u8"},
    "8a7f589fa689459ea471741386862155":{
      "scriptId":"u9"},
    "3b15317b990444c1a6a111cbd126da5e":{
      "scriptId":"u10"},
    "f385d554606d4264b675424bb19bde93":{
      "scriptId":"u11"},
    "5b5f1a9b40884dd397b5c19239173a09":{
      "scriptId":"u12"},
    "8df4ae7d7e6c48bbb040528932c829ac":{
      "scriptId":"u13"},
    "c68be6fa2a6a4d878b85ba21fb516075":{
      "scriptId":"u14"},
    "a9cbd6f5f73944d5b3f15f4465525ab8":{
      "scriptId":"u15"},
    "2a9fef5c1b404a35a786b9544f759c30":{
      "scriptId":"u16"},
    "c0f833565eb34917b759ca80de53e059":{
      "scriptId":"u17"},
    "938bc09828af4f259271db4b363b5d6e":{
      "scriptId":"u18"}}});