
@startuml
:用户:--->:学生:
:用户:--->:老师:
:学生:-->(查看自己成绩)
:用户:--->(登录、登出)
:学生:--->(选择课程)
:学生:--->(选择学期)
:老师:--->(修改信息)
:学生:-->(查看作业列表)
:老师:-->(查看学生成绩)
:老师:-->(对学生作业分项打分)
:老师:-->(查看学生信息)
:老师:-->(选择班级)
:老师:-->(查看该班级学生列表)
:老师:-->(发布作业链接)
@enduml